apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
spec:
  selector:
    matchLabels:
      app: redis
  serviceName: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: {{ .Values.images.redis }}
          imagePullPolicy: Always
          ports:
            - containerPort: 6379
              name: redis
          env:
            {{- range .Values.env }}
            - name: {{ .identifier }}
              value: {{ .value | quote }}
            {{- end }}
          volumeMounts:
            - name: redis-mount
              mountPath: /data
          args:
            {{- if eq .Values.parameterGroupsEnabled.persistentStorage true }}
            - "--save"
            - {{ .Values.parameterGroupsMap.REDIS_SAVE_INTERVAL }}
            - 1
            {{- end }}
      volumes:
        - name: redis-mount
          hostPath:
            path: {{ $.Values.storage.redis.hostPath }}
